apiVersion: v1
kind: page
spec:
  id: ux0chdh
  title: Default page
  content:
    - component: PageRow
      name: pageRow
      children:
        - component: TextField
          name: textField
          props:
            fullWidth: true
            label: Write prompt here..
          layout:
            columnSize: 1.853658536585366
        - component: Button
          name: button1
          props:
            onClick:
              $$jsExpressionAction: |+
                query2.call();

                text.value = textField.value;
                //textField.value = '';

            content: Submit
            size: medium
          layout:
            columnSize: 0.14634146341463414
    - component: PageRow
      name: pageRow2
      children:
        - component: Text
          name: text
    - component: PageRow
      name: pageRow4
      children:
        - component: DataGrid
          name: dataGrid
          props:
            rows:
              $$jsExpression: |
                query2.data
            columns:
              - field: role
                type: string
              - field: content
                type: string
                width: 693
  queries:
    - name: query
      query:
        function: query_open3
        kind: local
      parameters:
        - name: prompt
          value:
            $$jsExpression: |
              textField.value
      mode: mutation
    - name: query2
      mode: mutation
      query:
        function: query_open4
        kind: local
      parameters:
        - name: prompt
          value:
            $$jsExpression: |
              textField.value
      enabled: true
    - name: query3
      query:
        function: query_open5
        kind: local
      parameters:
        - name: prompt
          value:
            $$jsExpression: |
              textField.value
